name: messenger-min

services:
  app:
    image: ${DOCKER_USERNAME}/messenger-min-app:${IMAGE_TAG}
    container_name: messenger-min-app
    hostname: messenger-min-app
    ports:
      - "4052:4052"
    restart: unless-stopped