name: CD application

on:
  workflow_run:
    workflows:
      - "CI application"
    types:
      - completed

  workflow_dispatch:
    inputs:
      reason:
        description: "Name the reason"
        default: "Update"
        required: true
      version:
        description: 'Version'
        required: true
        default: 'latest'
      run_id:
        description: 'CI workflow Run ID'
        required: false
        default: ''

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: application
          path: build/libs/
          run-id: ${{ inputs.run_id || github.event.workflow_run.id }}
          github-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/messenger-min-app:prod

      - name: Update Stack Portainer
        run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK }}"